shallow_clone: true

platform:
  - x86
  # - x64

configuration:
  - Debug
  # - Release

image:
  - Visual Studio 2015
  # - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86
  - C:\mkl\

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
  - ps: |
      if (![IO.File]::Exists("C:\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe does not exist. Preparing to install MKL ..'
        Start-FileDownload 'http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12079/w_mkl_2018.0.124.exe' -FileName 'C:\w_mkl_2018.0.124.exe'
        C:\w_mkl_2018.0.124.exe -s -l c:\sik.log -a install --eula=accept --components=all --output='C:\install-mkl.log' --installdir='C:\xxx'
        # C:\Users\appveyor\Downloads\Intel\w_mkl_2018.0.124\setup.exe install --components=all --eula=accept --output='C:\install-mkl.log' --installdir='C:\xxx'
        ECHO 'done'
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
  - ps: |
      if (![IO.File]::Exists("C:\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe is missing'
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
  - ps: |
      if (![IO.File]::Exists("C:\sik.log")) {
        ECHO 'sik.log is missing'
      }
      else{
        ECHO 'sik.log already existed'
      }
  # - C:\w_mkl_2018.0.124.exe --s --l c:\sik.log --x
  # # - type c:\sik.log
  # - C:\Users\appveyor\Downloads\Intel\w_mkl_2018.0.124\setup.exe --help
  # # - C:\w_mkl_2018.0.124.exe -s -x -l c:\sik.log
  # # - type c:\sik.log
  # # - C:\w_mkl_2018.0.124.exe --s --l c:\sik.log -a "--components=all --eula=accept --output='C:\install-mkl.log' --installdir='C:\Program Files (x86)\IntelSWTools' --s "
  # # --a --s --components=all -eula=accept --output='C:\install-mkl.log' --installdir='C:\Program Files (x86)\IntelSWTools'
  - ps: |
      if (![IO.File]::Exists("C:\sik.log")) {
        ECHO 'sik.log is missing'
      }
      else{
        ECHO 'sik.log already existed'
        TYPE c:\sik.log
      }
  # - ps: cmake -P .continuous_integration/InstallMKL.cmake 


before_build:
  - ps: |
      mkdir build
      cd build
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          $env:generator="Visual Studio 14 2015"
      } else {
          $env:generator="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      # cmake .. -G "$env:generator"
      cmake ..

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - ctest -j2

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
