shallow_clone: true

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2015
  - Visual Studio 2017

cache:
  - C:\cmake-3.8.0-win32-x86
  - C:\mkl\

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: |
      if (![IO.File]::Exists("C:\cmake-3.8.0-win32-x86\bin\cmake.exe")) {
        Start-FileDownload 'https://cmake.org/files/v3.8/cmake-3.8.0-win32-x86.zip'
        7z x -y cmake-3.8.0-win32-x86.zip -oC:\
      }
      $env:PATH="C:\cmake-3.8.0-win32-x86\bin;$env:PATH"
  - ps: |
      if (![IO.File]::Exists("C:\mkl\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe is missing'
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
  - ps: |
      if (![IO.File]::Exists("C:\mkl\w_mkl_2018.0.124.exe")) {
        MD C:\mkl\
        DIR C:\
        Start-FileDownload 'http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/12079/w_mkl_2018.0.124.exe' -FileName 'C:\mkl\w_mkl_2018.0.124.exe'
        C:\mkl\w_mkl_2018.0.124.exe -s -x -l c:\sik.log
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
  - ps: |
      if (![IO.File]::Exists("C:\mkl\w_mkl_2018.0.124.exe")) {
        ECHO 'w_mkl_2018.0.124.exe is missing'
      }
      else{
        ECHO 'w_mkl_2018.0.124.exe already existed'
      }
  - C:\mkl\w_mkl_2018.0.124.exe -s -x -l c:\sik.log
  - type c:\sik.log
  # - C:\mkl\w_mkl_2018.0.124.exe -s --components=all -eula=accept --output=C:\mkl\install-mkl.log --installdir='C:\Program Files (x86)\IntelSWTools'
  # - ps: cmake -P .continuous_integration/InstallMKL.cmake 


before_build:
  - ps: |
      mkdir build
      cd build
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
          $env:generator="Visual Studio 14 2015"
      } else {
          $env:generator="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
          $env:generator="$env:generator Win64"
      }
      echo generator="$env:generator"
      cmake .. -G "$env:generator"

build_script:
  - cmake --build . --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - ctest -j2

deploy: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
